# Generated by Django 5.0.3 on 2024-04-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0002_examen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examen_detallado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('seleccionado', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='examen',
            name='descripcion',
            field=models.TextField(verbose_name=500),
        ),
    ]
