# Generated by Django 5.0.3 on 2024-04-13 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0004_rename_nombre_examen_titulo_examen_precio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examen',
            name='descripcion',
        ),
    ]
