# Generated by Django 5.0.3 on 2024-04-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0005_remove_examen_descripcion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Examen_detallado',
        ),
        migrations.AddField(
            model_name='examen',
            name='paquete',
            field=models.ManyToManyField(to='AppWeb.examen'),
        ),
    ]
