# Generated by Django 5.0.3 on 2024-04-14 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0008_examen_imagen_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='examen',
            name='examenes',
        ),
        migrations.AddField(
            model_name='examen',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examenes', to='AppWeb.categoria'),
        ),
        migrations.CreateModel(
            name='SubcategoriaExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='AppWeb.examen')),
            ],
        ),
    ]
