# Generated by Django 5.0.3 on 2024-04-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0010_alter_customuser_email_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategoriaexamen',
            name='mensaje_para_reseña',
            field=models.TextField(default='Mensaje predeterminado'),
        ),
    ]
