# Generated by Django 5.0.3 on 2024-04-28 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0013_paqueteexamen_alter_examen_categoria_alter_examen_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examen',
            name='paquete',
        ),
        migrations.RemoveField(
            model_name='subcategoriaexamen',
            name='paquete',
        ),
        migrations.AlterField(
            model_name='examen',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examenes', to='AppWeb.categoria'),
        ),
        migrations.AlterField(
            model_name='examen',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='PaqueteExamen',
        ),
    ]
