# Generated by Django 5.0.3 on 2024-04-29 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0014_remove_examen_paquete_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Examen',
            new_name='PaqueteExamen',
        ),
    ]
