# Generated by Django 5.0.3 on 2024-05-07 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0015_alter_customuser_apellido_alter_customuser_comuna_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
