# Generated by Django 5.0.3 on 2024-04-29 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0015_rename_examen_paqueteexamen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategoriaexamen',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
