# Generated by Django 5.0.3 on 2024-04-30 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0016_alter_subcategoriaexamen_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen_url', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='paqueteexamen',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='subcategoriaexamen',
            name='examen',
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('costo_fijo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen_url', models.CharField(max_length=200, null=True)),
                ('examenes', models.ManyToManyField(to='AppWeb.examen')),
            ],
        ),
        migrations.CreateModel(
            name='ElementoCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppWeb.paquete')),
            ],
        ),
        migrations.DeleteModel(
            name='CarritoDeCompras',
        ),
        migrations.DeleteModel(
            name='PaqueteExamen',
        ),
        migrations.DeleteModel(
            name='SubcategoriaExamen',
        ),
    ]
