# Generated by Django 5.0.3 on 2024-04-30 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0017_examen_remove_paqueteexamen_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
