# Generated by Django 5.0.3 on 2024-05-07 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0017_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
