# Generated by Django 5.0.3 on 2024-05-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0018_alter_examen_id_alter_paquete_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elementocarrito',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='elementocarrito',
            name='examenes',
            field=models.ManyToManyField(to='AppWeb.examen'),
        ),
        migrations.AlterField(
            model_name='examen',
            name='imagen_url',
            field=models.ImageField(blank=True, null=True, upload_to='paquetes_imagenes/'),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='imagen_url',
            field=models.ImageField(blank=True, null=True, upload_to='paquetes_imagenes/'),
        ),
    ]
