# Generated by Django 5.0.3 on 2024-05-01 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0019_remove_elementocarrito_cantidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elementocarrito',
            name='examenes',
        ),
        migrations.AddField(
            model_name='elementocarrito',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='elementocarrito',
            name='examen',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AppWeb.examen'),
        ),
    ]
