# Generated by Django 5.0.3 on 2024-05-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0024_alter_categoria_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='imagen',
        ),
        migrations.AddField(
            model_name='categoria',
            name='imagen_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
