# Generated by Django 5.0.3 on 2024-05-07 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0026_carrito_itemcarrito_carrito_productos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Derivacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=1, max_digits=10)),
                ('imagen_url', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='categoria',
            name='precio',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
