# Generated by Django 5.0.3 on 2024-05-12 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0030_remove_itemcarrito_diagnostico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppWeb.carrito')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppWeb.item')),
            ],
        ),
    ]
