# Generated by Django 5.0.3 on 2024-05-12 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0031_itemcarrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='precio',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='derivacion',
            name='precio',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
