# Generated by Django 5.0.3 on 2024-05-13 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0018_alter_customuser_managers'),
        ('AppWeb', '0032_alter_categoria_precio_alter_derivacion_precio'),
    ]

    operations = [
    ]
