# Generated by Django 5.0.6 on 2024-06-11 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0036_alter_carrito_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('costo_total', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('numero', models.PositiveIntegerField(blank=True, editable=False, null=True, unique=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompraItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('costo', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='AppWeb.compra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppWeb.item')),
            ],
        ),
        migrations.DeleteModel(
            name='CompraHistorica',
        ),
    ]
